{"name": "Тест получения заказа авторизованного пользователя", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "@pytest.fixture\n    def user_data_and_token():\n        payload = helpers.payload\n        response = requests.post(UrlsConstants.CREATE_USER, data=payload)\n>       token = response.json()['accessToken']\nE       KeyError: 'accessToken'\n\ntests\\conftest.py:11: KeyError"}, "description": "Получаем информация по заказу", "start": 1727882463674, "stop": 1727882463674, "uuid": "841edc34-d6bd-4f89-a472-e9ed531126ae", "historyId": "812703102737b3c895e798b661aa47de", "testCaseId": "812703102737b3c895e798b661aa47de", "fullName": "tests.test_api_get_user_orders.TestApiGetUserOrders#test_auth_user_get_order_successful", "labels": [{"name": "feature", "value": "Проверка получения заказа конкретного пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_get_user_orders"}, {"name": "subSuite", "value": "TestApiGetUserOrders"}, {"name": "host", "value": "DESKTOP-E2MLG10"}, {"name": "thread", "value": "14732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_get_user_orders"}]}